vim.opt.incsearch = true
vim.opt.ignorecase = true
vim.opt.hlsearch = true
vim.opt.smartcase = true
vim.opt.autoindent = true
vim.opt.backspace = "indent,eol,start"
vim.opt.hidden = true
vim.opt.ruler = true
vim.opt.wildmenu = true
vim.opt.swapfile = false
vim.opt.equalalways = false
vim.opt.signcolumn = "yes"
--vim.opt.colorcolumn=120
vim.opt.relativenumber = true
vim.opt.number = true
vim.opt.tabstop = 4
vim.opt.softtabstop = 4
vim.opt.shiftwidth = 4
vim.opt.expandtab = true
vim.opt.completeopt = { "menu", "menuone", "noselect" }
vim.opt.wrap = false
vim.opt.ch = 1
vim.opt.cmdheight = 0
vim.o.updatetime = 50
vim.g.mapleader = " "
